# -*- coding: utf-8 -*-
"""SL2 FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147r88ceF-42VrGDOBZC1oIRd91U5lFvb
"""

import streamlit as st
import pandas as pd
import numpy as np

# ---------------------------------------------------
# 1. REAL COAL PLANT DATA (YOUR PROVIDED DATA)
# ---------------------------------------------------
plants_data = [
    {'plant_name':'North Karanpura STPP','coal_tons':7969147,'TSP':23907,'PM10':14344,'PM2.5':12910,'SO2':55784},
    {'plant_name':'Patratu STPP','coal_tons':8229144,'TSP':28802,'PM10':17281,'PM2.5':15553,'SO2':41146},
    {'plant_name':'Tenughat TPS','coal_tons':2233800,'TSP':15637,'PM10':9382,'PM2.5':8444,'SO2':13403},
    {'plant_name':'Talcher Kaniha','coal_tons':10704720,'TSP':42819,'PM10':25691,'PM2.5':23122,'SO2':85638},
    {'plant_name':'Darlipali','coal_tons':8563776,'TSP':29117,'PM10':17470,'PM2.5':15723,'SO2':33913},
    {'plant_name':'IB Thermal','coal_tons':9493650,'TSP':34177,'PM10':20506,'PM2.5':18456,'SO2':28196},
    {'plant_name':'Korba Super Thermal','coal_tons':9825216,'TSP':29476,'PM10':17685,'PM2.5':15917,'SO2':29181},
    {'plant_name':'Sipat Super Thermal','coal_tons':10233432,'TSP':34794,'PM10':20876,'PM2.5':18789,'SO2':50655}
]

df_plants = pd.DataFrame(plants_data)

# ---------------------------------------------------
# LEARN AVERAGE COAL EMISSION FACTORS
# ---------------------------------------------------
pollutants = ["TSP", "PM10", "PM2.5", "SO2"]
coal_EF_real = {pol: (df_plants[pol] / df_plants["coal_tons"]).mean() for pol in pollutants}

# ---------------------------------------------------
# BIOGAS EMISSION FACTORS (tons/ton fuel)
# ---------------------------------------------------
biogas_EF = {
    'TSP':   0.05/1000,
    'PM10':  0.05/1000,
    'PM2.5': 0.02/1000,
    'SO2':   0.01/1000,
    'NOx':   0.50/1000
}

# ---------------------------------------------------
# STREAMlit UI
# ---------------------------------------------------
st.title("Biogas & Coal Blending")
st.subheader("Calculate your emissions after blending biogas with coal")

st.markdown("---")

st.header("Plant Input Data")

col1, col2 = st.columns(2)

with col1:
    coal_consumption = st.number_input("Coal consumption (tons/year):", min_value=0.0, value=1000000.0)

with col2:
    biogas_frac = st.slider("Biogas blending fraction:", 0.0, 1.0, 0.1)

st.markdown("### Baseline Emissions (tons/year)")
col3, col4, col5, col6 = st.columns(4)

with col3:
    "Total Suspended Particulates"
    TSP_in = st.number_input("TSP", min_value=0.0, value=500.0)
with col4:
    PM10_in = st.number_input("PM10", min_value=0.0, value=400.0)
with col5:
    PM25_in = st.number_input("PM2.5", min_value=0.0, value=300.0)
with col6:
    SO2_in = st.number_input("SO2", min_value=0.0, value=800.0)

st.markdown("### Pollution Control Systems")

col7, col8 = st.columns(2)

with col7:
    "Electrostatic Precipitator"
    ESP = st.slider("ESP Efficiency (%)", 0, 100, 90)
with col8:
    "*Flue Gas Desulfurization*"

    FGD = st.slider("FGD Efficiency (%)", 0, 100, 70)

# ---------------------------------------------------
# CALCULATE OUTPUTS
# ---------------------------------------------------
coal_share = 1 - biogas_frac
bio_share = biogas_frac

coal_baseline = {
    "TSP": TSP_in,
    "PM10": PM10_in,
    "PM2.5": PM25_in,
    "SO2": SO2_in,
    "NOx": 0.0
}

results = {}

for pol in coal_baseline:

    coal_part = coal_baseline[pol] * coal_share
    bio_part = biogas_EF[pol] * coal_consumption * bio_share
    total = coal_part + bio_part

    if pol in ["TSP","PM10","PM2.5"]:
        total *= (1 - ESP/100)

    if pol == "SO2":
        total *= (1 - FGD/100)

    results[pol] = total


# ---------------------------------------------------
# OUTPUT TABLE DISPLAY
# ---------------------------------------------------
df_out = pd.DataFrame({
    "Pollutant": list(coal_baseline.keys()),
    "Baseline_Emissions (tons)": list(coal_baseline.values()),
    "Blended_Emissions (tons)": [results[p] for p in coal_baseline],
    "Reduction (%)": [
        round((1 - results[p]/coal_baseline[p])*100,2) if coal_baseline[p] > 0 else "N/A"
        for p in coal_baseline.keys()
    ]
})

st.markdown("## Final Results")

st.dataframe(df_out, use_container_width=True)

# Show key reduction indicators
st.markdown("##  Summary")

for pol in ["TSP", "PM10", "PM2.5", "SO2"]:
    reduction = df_out.loc[df_out["Pollutant"] == pol, "Reduction (%)"].values[0]
    st.success(f"**{pol} Reduction:** {reduction}%")